
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  AUTHOR: 'AUTHOR',
  AGENT: 'AGENT',
  GUEST: 'GUEST'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const Visibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  UNLISTED: 'UNLISTED',
  DRAFT: 'DRAFT'
} as const

export type Visibility = (typeof Visibility)[keyof typeof Visibility]
