
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PostRedirect` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PostRedirect
 * 
 */
export type PostRedirectModel = runtime.Types.Result.DefaultSelection<Prisma.$PostRedirectPayload>

export type AggregatePostRedirect = {
  _count: PostRedirectCountAggregateOutputType | null
  _min: PostRedirectMinAggregateOutputType | null
  _max: PostRedirectMaxAggregateOutputType | null
}

export type PostRedirectMinAggregateOutputType = {
  id: string | null
  slug: string | null
  postId: string | null
  createdAt: Date | null
}

export type PostRedirectMaxAggregateOutputType = {
  id: string | null
  slug: string | null
  postId: string | null
  createdAt: Date | null
}

export type PostRedirectCountAggregateOutputType = {
  id: number
  slug: number
  postId: number
  createdAt: number
  _all: number
}


export type PostRedirectMinAggregateInputType = {
  id?: true
  slug?: true
  postId?: true
  createdAt?: true
}

export type PostRedirectMaxAggregateInputType = {
  id?: true
  slug?: true
  postId?: true
  createdAt?: true
}

export type PostRedirectCountAggregateInputType = {
  id?: true
  slug?: true
  postId?: true
  createdAt?: true
  _all?: true
}

export type PostRedirectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PostRedirect to aggregate.
   */
  where?: Prisma.PostRedirectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostRedirects to fetch.
   */
  orderBy?: Prisma.PostRedirectOrderByWithRelationInput | Prisma.PostRedirectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PostRedirectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostRedirects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostRedirects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PostRedirects
  **/
  _count?: true | PostRedirectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PostRedirectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PostRedirectMaxAggregateInputType
}

export type GetPostRedirectAggregateType<T extends PostRedirectAggregateArgs> = {
      [P in keyof T & keyof AggregatePostRedirect]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePostRedirect[P]>
    : Prisma.GetScalarType<T[P], AggregatePostRedirect[P]>
}




export type PostRedirectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostRedirectWhereInput
  orderBy?: Prisma.PostRedirectOrderByWithAggregationInput | Prisma.PostRedirectOrderByWithAggregationInput[]
  by: Prisma.PostRedirectScalarFieldEnum[] | Prisma.PostRedirectScalarFieldEnum
  having?: Prisma.PostRedirectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PostRedirectCountAggregateInputType | true
  _min?: PostRedirectMinAggregateInputType
  _max?: PostRedirectMaxAggregateInputType
}

export type PostRedirectGroupByOutputType = {
  id: string
  slug: string
  postId: string
  createdAt: Date
  _count: PostRedirectCountAggregateOutputType | null
  _min: PostRedirectMinAggregateOutputType | null
  _max: PostRedirectMaxAggregateOutputType | null
}

export type GetPostRedirectGroupByPayload<T extends PostRedirectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PostRedirectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PostRedirectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PostRedirectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PostRedirectGroupByOutputType[P]>
      }
    >
  >



export type PostRedirectWhereInput = {
  AND?: Prisma.PostRedirectWhereInput | Prisma.PostRedirectWhereInput[]
  OR?: Prisma.PostRedirectWhereInput[]
  NOT?: Prisma.PostRedirectWhereInput | Prisma.PostRedirectWhereInput[]
  id?: Prisma.StringFilter<"PostRedirect"> | string
  slug?: Prisma.StringFilter<"PostRedirect"> | string
  postId?: Prisma.StringFilter<"PostRedirect"> | string
  createdAt?: Prisma.DateTimeFilter<"PostRedirect"> | Date | string
  post?: Prisma.XOR<Prisma.PostScalarRelationFilter, Prisma.PostWhereInput>
}

export type PostRedirectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  post?: Prisma.PostOrderByWithRelationInput
}

export type PostRedirectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.PostRedirectWhereInput | Prisma.PostRedirectWhereInput[]
  OR?: Prisma.PostRedirectWhereInput[]
  NOT?: Prisma.PostRedirectWhereInput | Prisma.PostRedirectWhereInput[]
  postId?: Prisma.StringFilter<"PostRedirect"> | string
  createdAt?: Prisma.DateTimeFilter<"PostRedirect"> | Date | string
  post?: Prisma.XOR<Prisma.PostScalarRelationFilter, Prisma.PostWhereInput>
}, "id" | "slug">

export type PostRedirectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PostRedirectCountOrderByAggregateInput
  _max?: Prisma.PostRedirectMaxOrderByAggregateInput
  _min?: Prisma.PostRedirectMinOrderByAggregateInput
}

export type PostRedirectScalarWhereWithAggregatesInput = {
  AND?: Prisma.PostRedirectScalarWhereWithAggregatesInput | Prisma.PostRedirectScalarWhereWithAggregatesInput[]
  OR?: Prisma.PostRedirectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PostRedirectScalarWhereWithAggregatesInput | Prisma.PostRedirectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PostRedirect"> | string
  slug?: Prisma.StringWithAggregatesFilter<"PostRedirect"> | string
  postId?: Prisma.StringWithAggregatesFilter<"PostRedirect"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PostRedirect"> | Date | string
}

export type PostRedirectCreateInput = {
  id?: string
  slug: string
  createdAt?: Date | string
  post: Prisma.PostCreateNestedOneWithoutRedirectsInput
}

export type PostRedirectUncheckedCreateInput = {
  id?: string
  slug: string
  postId: string
  createdAt?: Date | string
}

export type PostRedirectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  post?: Prisma.PostUpdateOneRequiredWithoutRedirectsNestedInput
}

export type PostRedirectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostRedirectCreateManyInput = {
  id?: string
  slug: string
  postId: string
  createdAt?: Date | string
}

export type PostRedirectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostRedirectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostRedirectListRelationFilter = {
  every?: Prisma.PostRedirectWhereInput
  some?: Prisma.PostRedirectWhereInput
  none?: Prisma.PostRedirectWhereInput
}

export type PostRedirectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PostRedirectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PostRedirectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PostRedirectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PostRedirectCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.PostRedirectCreateWithoutPostInput, Prisma.PostRedirectUncheckedCreateWithoutPostInput> | Prisma.PostRedirectCreateWithoutPostInput[] | Prisma.PostRedirectUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.PostRedirectCreateOrConnectWithoutPostInput | Prisma.PostRedirectCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.PostRedirectCreateManyPostInputEnvelope
  connect?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
}

export type PostRedirectUncheckedCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.PostRedirectCreateWithoutPostInput, Prisma.PostRedirectUncheckedCreateWithoutPostInput> | Prisma.PostRedirectCreateWithoutPostInput[] | Prisma.PostRedirectUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.PostRedirectCreateOrConnectWithoutPostInput | Prisma.PostRedirectCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.PostRedirectCreateManyPostInputEnvelope
  connect?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
}

export type PostRedirectUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.PostRedirectCreateWithoutPostInput, Prisma.PostRedirectUncheckedCreateWithoutPostInput> | Prisma.PostRedirectCreateWithoutPostInput[] | Prisma.PostRedirectUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.PostRedirectCreateOrConnectWithoutPostInput | Prisma.PostRedirectCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.PostRedirectUpsertWithWhereUniqueWithoutPostInput | Prisma.PostRedirectUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.PostRedirectCreateManyPostInputEnvelope
  set?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
  disconnect?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
  delete?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
  connect?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
  update?: Prisma.PostRedirectUpdateWithWhereUniqueWithoutPostInput | Prisma.PostRedirectUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.PostRedirectUpdateManyWithWhereWithoutPostInput | Prisma.PostRedirectUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.PostRedirectScalarWhereInput | Prisma.PostRedirectScalarWhereInput[]
}

export type PostRedirectUncheckedUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.PostRedirectCreateWithoutPostInput, Prisma.PostRedirectUncheckedCreateWithoutPostInput> | Prisma.PostRedirectCreateWithoutPostInput[] | Prisma.PostRedirectUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.PostRedirectCreateOrConnectWithoutPostInput | Prisma.PostRedirectCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.PostRedirectUpsertWithWhereUniqueWithoutPostInput | Prisma.PostRedirectUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.PostRedirectCreateManyPostInputEnvelope
  set?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
  disconnect?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
  delete?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
  connect?: Prisma.PostRedirectWhereUniqueInput | Prisma.PostRedirectWhereUniqueInput[]
  update?: Prisma.PostRedirectUpdateWithWhereUniqueWithoutPostInput | Prisma.PostRedirectUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.PostRedirectUpdateManyWithWhereWithoutPostInput | Prisma.PostRedirectUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.PostRedirectScalarWhereInput | Prisma.PostRedirectScalarWhereInput[]
}

export type PostRedirectCreateWithoutPostInput = {
  id?: string
  slug: string
  createdAt?: Date | string
}

export type PostRedirectUncheckedCreateWithoutPostInput = {
  id?: string
  slug: string
  createdAt?: Date | string
}

export type PostRedirectCreateOrConnectWithoutPostInput = {
  where: Prisma.PostRedirectWhereUniqueInput
  create: Prisma.XOR<Prisma.PostRedirectCreateWithoutPostInput, Prisma.PostRedirectUncheckedCreateWithoutPostInput>
}

export type PostRedirectCreateManyPostInputEnvelope = {
  data: Prisma.PostRedirectCreateManyPostInput | Prisma.PostRedirectCreateManyPostInput[]
  skipDuplicates?: boolean
}

export type PostRedirectUpsertWithWhereUniqueWithoutPostInput = {
  where: Prisma.PostRedirectWhereUniqueInput
  update: Prisma.XOR<Prisma.PostRedirectUpdateWithoutPostInput, Prisma.PostRedirectUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.PostRedirectCreateWithoutPostInput, Prisma.PostRedirectUncheckedCreateWithoutPostInput>
}

export type PostRedirectUpdateWithWhereUniqueWithoutPostInput = {
  where: Prisma.PostRedirectWhereUniqueInput
  data: Prisma.XOR<Prisma.PostRedirectUpdateWithoutPostInput, Prisma.PostRedirectUncheckedUpdateWithoutPostInput>
}

export type PostRedirectUpdateManyWithWhereWithoutPostInput = {
  where: Prisma.PostRedirectScalarWhereInput
  data: Prisma.XOR<Prisma.PostRedirectUpdateManyMutationInput, Prisma.PostRedirectUncheckedUpdateManyWithoutPostInput>
}

export type PostRedirectScalarWhereInput = {
  AND?: Prisma.PostRedirectScalarWhereInput | Prisma.PostRedirectScalarWhereInput[]
  OR?: Prisma.PostRedirectScalarWhereInput[]
  NOT?: Prisma.PostRedirectScalarWhereInput | Prisma.PostRedirectScalarWhereInput[]
  id?: Prisma.StringFilter<"PostRedirect"> | string
  slug?: Prisma.StringFilter<"PostRedirect"> | string
  postId?: Prisma.StringFilter<"PostRedirect"> | string
  createdAt?: Prisma.DateTimeFilter<"PostRedirect"> | Date | string
}

export type PostRedirectCreateManyPostInput = {
  id?: string
  slug: string
  createdAt?: Date | string
}

export type PostRedirectUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostRedirectUncheckedUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PostRedirectUncheckedUpdateManyWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PostRedirectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  postId?: boolean
  createdAt?: boolean
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["postRedirect"]>

export type PostRedirectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  postId?: boolean
  createdAt?: boolean
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["postRedirect"]>

export type PostRedirectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  postId?: boolean
  createdAt?: boolean
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["postRedirect"]>

export type PostRedirectSelectScalar = {
  id?: boolean
  slug?: boolean
  postId?: boolean
  createdAt?: boolean
}

export type PostRedirectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "slug" | "postId" | "createdAt", ExtArgs["result"]["postRedirect"]>
export type PostRedirectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}
export type PostRedirectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}
export type PostRedirectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}

export type $PostRedirectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PostRedirect"
  objects: {
    post: Prisma.$PostPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    slug: string
    postId: string
    createdAt: Date
  }, ExtArgs["result"]["postRedirect"]>
  composites: {}
}

export type PostRedirectGetPayload<S extends boolean | null | undefined | PostRedirectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload, S>

export type PostRedirectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PostRedirectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PostRedirectCountAggregateInputType | true
  }

export interface PostRedirectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PostRedirect'], meta: { name: 'PostRedirect' } }
  /**
   * Find zero or one PostRedirect that matches the filter.
   * @param {PostRedirectFindUniqueArgs} args - Arguments to find a PostRedirect
   * @example
   * // Get one PostRedirect
   * const postRedirect = await prisma.postRedirect.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PostRedirectFindUniqueArgs>(args: Prisma.SelectSubset<T, PostRedirectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PostRedirectClient<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PostRedirect that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PostRedirectFindUniqueOrThrowArgs} args - Arguments to find a PostRedirect
   * @example
   * // Get one PostRedirect
   * const postRedirect = await prisma.postRedirect.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PostRedirectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PostRedirectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PostRedirectClient<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PostRedirect that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostRedirectFindFirstArgs} args - Arguments to find a PostRedirect
   * @example
   * // Get one PostRedirect
   * const postRedirect = await prisma.postRedirect.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PostRedirectFindFirstArgs>(args?: Prisma.SelectSubset<T, PostRedirectFindFirstArgs<ExtArgs>>): Prisma.Prisma__PostRedirectClient<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PostRedirect that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostRedirectFindFirstOrThrowArgs} args - Arguments to find a PostRedirect
   * @example
   * // Get one PostRedirect
   * const postRedirect = await prisma.postRedirect.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PostRedirectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PostRedirectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PostRedirectClient<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PostRedirects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostRedirectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PostRedirects
   * const postRedirects = await prisma.postRedirect.findMany()
   * 
   * // Get first 10 PostRedirects
   * const postRedirects = await prisma.postRedirect.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const postRedirectWithIdOnly = await prisma.postRedirect.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PostRedirectFindManyArgs>(args?: Prisma.SelectSubset<T, PostRedirectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PostRedirect.
   * @param {PostRedirectCreateArgs} args - Arguments to create a PostRedirect.
   * @example
   * // Create one PostRedirect
   * const PostRedirect = await prisma.postRedirect.create({
   *   data: {
   *     // ... data to create a PostRedirect
   *   }
   * })
   * 
   */
  create<T extends PostRedirectCreateArgs>(args: Prisma.SelectSubset<T, PostRedirectCreateArgs<ExtArgs>>): Prisma.Prisma__PostRedirectClient<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PostRedirects.
   * @param {PostRedirectCreateManyArgs} args - Arguments to create many PostRedirects.
   * @example
   * // Create many PostRedirects
   * const postRedirect = await prisma.postRedirect.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PostRedirectCreateManyArgs>(args?: Prisma.SelectSubset<T, PostRedirectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PostRedirects and returns the data saved in the database.
   * @param {PostRedirectCreateManyAndReturnArgs} args - Arguments to create many PostRedirects.
   * @example
   * // Create many PostRedirects
   * const postRedirect = await prisma.postRedirect.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PostRedirects and only return the `id`
   * const postRedirectWithIdOnly = await prisma.postRedirect.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PostRedirectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PostRedirectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PostRedirect.
   * @param {PostRedirectDeleteArgs} args - Arguments to delete one PostRedirect.
   * @example
   * // Delete one PostRedirect
   * const PostRedirect = await prisma.postRedirect.delete({
   *   where: {
   *     // ... filter to delete one PostRedirect
   *   }
   * })
   * 
   */
  delete<T extends PostRedirectDeleteArgs>(args: Prisma.SelectSubset<T, PostRedirectDeleteArgs<ExtArgs>>): Prisma.Prisma__PostRedirectClient<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PostRedirect.
   * @param {PostRedirectUpdateArgs} args - Arguments to update one PostRedirect.
   * @example
   * // Update one PostRedirect
   * const postRedirect = await prisma.postRedirect.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PostRedirectUpdateArgs>(args: Prisma.SelectSubset<T, PostRedirectUpdateArgs<ExtArgs>>): Prisma.Prisma__PostRedirectClient<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PostRedirects.
   * @param {PostRedirectDeleteManyArgs} args - Arguments to filter PostRedirects to delete.
   * @example
   * // Delete a few PostRedirects
   * const { count } = await prisma.postRedirect.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PostRedirectDeleteManyArgs>(args?: Prisma.SelectSubset<T, PostRedirectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PostRedirects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostRedirectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PostRedirects
   * const postRedirect = await prisma.postRedirect.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PostRedirectUpdateManyArgs>(args: Prisma.SelectSubset<T, PostRedirectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PostRedirects and returns the data updated in the database.
   * @param {PostRedirectUpdateManyAndReturnArgs} args - Arguments to update many PostRedirects.
   * @example
   * // Update many PostRedirects
   * const postRedirect = await prisma.postRedirect.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PostRedirects and only return the `id`
   * const postRedirectWithIdOnly = await prisma.postRedirect.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PostRedirectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PostRedirectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PostRedirect.
   * @param {PostRedirectUpsertArgs} args - Arguments to update or create a PostRedirect.
   * @example
   * // Update or create a PostRedirect
   * const postRedirect = await prisma.postRedirect.upsert({
   *   create: {
   *     // ... data to create a PostRedirect
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PostRedirect we want to update
   *   }
   * })
   */
  upsert<T extends PostRedirectUpsertArgs>(args: Prisma.SelectSubset<T, PostRedirectUpsertArgs<ExtArgs>>): Prisma.Prisma__PostRedirectClient<runtime.Types.Result.GetResult<Prisma.$PostRedirectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PostRedirects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostRedirectCountArgs} args - Arguments to filter PostRedirects to count.
   * @example
   * // Count the number of PostRedirects
   * const count = await prisma.postRedirect.count({
   *   where: {
   *     // ... the filter for the PostRedirects we want to count
   *   }
   * })
  **/
  count<T extends PostRedirectCountArgs>(
    args?: Prisma.Subset<T, PostRedirectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PostRedirectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PostRedirect.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostRedirectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PostRedirectAggregateArgs>(args: Prisma.Subset<T, PostRedirectAggregateArgs>): Prisma.PrismaPromise<GetPostRedirectAggregateType<T>>

  /**
   * Group by PostRedirect.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostRedirectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PostRedirectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PostRedirectGroupByArgs['orderBy'] }
      : { orderBy?: PostRedirectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PostRedirectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostRedirectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PostRedirect model
 */
readonly fields: PostRedirectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PostRedirect.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PostRedirectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  post<T extends Prisma.PostDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PostDefaultArgs<ExtArgs>>): Prisma.Prisma__PostClient<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PostRedirect model
 */
export interface PostRedirectFieldRefs {
  readonly id: Prisma.FieldRef<"PostRedirect", 'String'>
  readonly slug: Prisma.FieldRef<"PostRedirect", 'String'>
  readonly postId: Prisma.FieldRef<"PostRedirect", 'String'>
  readonly createdAt: Prisma.FieldRef<"PostRedirect", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PostRedirect findUnique
 */
export type PostRedirectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * Filter, which PostRedirect to fetch.
   */
  where: Prisma.PostRedirectWhereUniqueInput
}

/**
 * PostRedirect findUniqueOrThrow
 */
export type PostRedirectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * Filter, which PostRedirect to fetch.
   */
  where: Prisma.PostRedirectWhereUniqueInput
}

/**
 * PostRedirect findFirst
 */
export type PostRedirectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * Filter, which PostRedirect to fetch.
   */
  where?: Prisma.PostRedirectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostRedirects to fetch.
   */
  orderBy?: Prisma.PostRedirectOrderByWithRelationInput | Prisma.PostRedirectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PostRedirects.
   */
  cursor?: Prisma.PostRedirectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostRedirects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostRedirects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostRedirects.
   */
  distinct?: Prisma.PostRedirectScalarFieldEnum | Prisma.PostRedirectScalarFieldEnum[]
}

/**
 * PostRedirect findFirstOrThrow
 */
export type PostRedirectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * Filter, which PostRedirect to fetch.
   */
  where?: Prisma.PostRedirectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostRedirects to fetch.
   */
  orderBy?: Prisma.PostRedirectOrderByWithRelationInput | Prisma.PostRedirectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PostRedirects.
   */
  cursor?: Prisma.PostRedirectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostRedirects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostRedirects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostRedirects.
   */
  distinct?: Prisma.PostRedirectScalarFieldEnum | Prisma.PostRedirectScalarFieldEnum[]
}

/**
 * PostRedirect findMany
 */
export type PostRedirectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * Filter, which PostRedirects to fetch.
   */
  where?: Prisma.PostRedirectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostRedirects to fetch.
   */
  orderBy?: Prisma.PostRedirectOrderByWithRelationInput | Prisma.PostRedirectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PostRedirects.
   */
  cursor?: Prisma.PostRedirectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostRedirects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostRedirects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostRedirects.
   */
  distinct?: Prisma.PostRedirectScalarFieldEnum | Prisma.PostRedirectScalarFieldEnum[]
}

/**
 * PostRedirect create
 */
export type PostRedirectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * The data needed to create a PostRedirect.
   */
  data: Prisma.XOR<Prisma.PostRedirectCreateInput, Prisma.PostRedirectUncheckedCreateInput>
}

/**
 * PostRedirect createMany
 */
export type PostRedirectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PostRedirects.
   */
  data: Prisma.PostRedirectCreateManyInput | Prisma.PostRedirectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PostRedirect createManyAndReturn
 */
export type PostRedirectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * The data used to create many PostRedirects.
   */
  data: Prisma.PostRedirectCreateManyInput | Prisma.PostRedirectCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PostRedirect update
 */
export type PostRedirectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * The data needed to update a PostRedirect.
   */
  data: Prisma.XOR<Prisma.PostRedirectUpdateInput, Prisma.PostRedirectUncheckedUpdateInput>
  /**
   * Choose, which PostRedirect to update.
   */
  where: Prisma.PostRedirectWhereUniqueInput
}

/**
 * PostRedirect updateMany
 */
export type PostRedirectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PostRedirects.
   */
  data: Prisma.XOR<Prisma.PostRedirectUpdateManyMutationInput, Prisma.PostRedirectUncheckedUpdateManyInput>
  /**
   * Filter which PostRedirects to update
   */
  where?: Prisma.PostRedirectWhereInput
  /**
   * Limit how many PostRedirects to update.
   */
  limit?: number
}

/**
 * PostRedirect updateManyAndReturn
 */
export type PostRedirectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * The data used to update PostRedirects.
   */
  data: Prisma.XOR<Prisma.PostRedirectUpdateManyMutationInput, Prisma.PostRedirectUncheckedUpdateManyInput>
  /**
   * Filter which PostRedirects to update
   */
  where?: Prisma.PostRedirectWhereInput
  /**
   * Limit how many PostRedirects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PostRedirect upsert
 */
export type PostRedirectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * The filter to search for the PostRedirect to update in case it exists.
   */
  where: Prisma.PostRedirectWhereUniqueInput
  /**
   * In case the PostRedirect found by the `where` argument doesn't exist, create a new PostRedirect with this data.
   */
  create: Prisma.XOR<Prisma.PostRedirectCreateInput, Prisma.PostRedirectUncheckedCreateInput>
  /**
   * In case the PostRedirect was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PostRedirectUpdateInput, Prisma.PostRedirectUncheckedUpdateInput>
}

/**
 * PostRedirect delete
 */
export type PostRedirectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
  /**
   * Filter which PostRedirect to delete.
   */
  where: Prisma.PostRedirectWhereUniqueInput
}

/**
 * PostRedirect deleteMany
 */
export type PostRedirectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PostRedirects to delete
   */
  where?: Prisma.PostRedirectWhereInput
  /**
   * Limit how many PostRedirects to delete.
   */
  limit?: number
}

/**
 * PostRedirect without action
 */
export type PostRedirectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostRedirect
   */
  select?: Prisma.PostRedirectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostRedirect
   */
  omit?: Prisma.PostRedirectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostRedirectInclude<ExtArgs> | null
}
