
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PostMetadata` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PostMetadata
 * 
 */
export type PostMetadataModel = runtime.Types.Result.DefaultSelection<Prisma.$PostMetadataPayload>

export type AggregatePostMetadata = {
  _count: PostMetadataCountAggregateOutputType | null
  _min: PostMetadataMinAggregateOutputType | null
  _max: PostMetadataMaxAggregateOutputType | null
}

export type PostMetadataMinAggregateOutputType = {
  id: string | null
  seoDescription: string | null
  coverImage: string | null
  postId: string | null
}

export type PostMetadataMaxAggregateOutputType = {
  id: string | null
  seoDescription: string | null
  coverImage: string | null
  postId: string | null
}

export type PostMetadataCountAggregateOutputType = {
  id: number
  seoDescription: number
  coverImage: number
  tags: number
  postId: number
  _all: number
}


export type PostMetadataMinAggregateInputType = {
  id?: true
  seoDescription?: true
  coverImage?: true
  postId?: true
}

export type PostMetadataMaxAggregateInputType = {
  id?: true
  seoDescription?: true
  coverImage?: true
  postId?: true
}

export type PostMetadataCountAggregateInputType = {
  id?: true
  seoDescription?: true
  coverImage?: true
  tags?: true
  postId?: true
  _all?: true
}

export type PostMetadataAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PostMetadata to aggregate.
   */
  where?: Prisma.PostMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostMetadata to fetch.
   */
  orderBy?: Prisma.PostMetadataOrderByWithRelationInput | Prisma.PostMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PostMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PostMetadata
  **/
  _count?: true | PostMetadataCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PostMetadataMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PostMetadataMaxAggregateInputType
}

export type GetPostMetadataAggregateType<T extends PostMetadataAggregateArgs> = {
      [P in keyof T & keyof AggregatePostMetadata]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePostMetadata[P]>
    : Prisma.GetScalarType<T[P], AggregatePostMetadata[P]>
}




export type PostMetadataGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostMetadataWhereInput
  orderBy?: Prisma.PostMetadataOrderByWithAggregationInput | Prisma.PostMetadataOrderByWithAggregationInput[]
  by: Prisma.PostMetadataScalarFieldEnum[] | Prisma.PostMetadataScalarFieldEnum
  having?: Prisma.PostMetadataScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PostMetadataCountAggregateInputType | true
  _min?: PostMetadataMinAggregateInputType
  _max?: PostMetadataMaxAggregateInputType
}

export type PostMetadataGroupByOutputType = {
  id: string
  seoDescription: string | null
  coverImage: string | null
  tags: string[]
  postId: string
  _count: PostMetadataCountAggregateOutputType | null
  _min: PostMetadataMinAggregateOutputType | null
  _max: PostMetadataMaxAggregateOutputType | null
}

export type GetPostMetadataGroupByPayload<T extends PostMetadataGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PostMetadataGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PostMetadataGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PostMetadataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PostMetadataGroupByOutputType[P]>
      }
    >
  >



export type PostMetadataWhereInput = {
  AND?: Prisma.PostMetadataWhereInput | Prisma.PostMetadataWhereInput[]
  OR?: Prisma.PostMetadataWhereInput[]
  NOT?: Prisma.PostMetadataWhereInput | Prisma.PostMetadataWhereInput[]
  id?: Prisma.StringFilter<"PostMetadata"> | string
  seoDescription?: Prisma.StringNullableFilter<"PostMetadata"> | string | null
  coverImage?: Prisma.StringNullableFilter<"PostMetadata"> | string | null
  tags?: Prisma.StringNullableListFilter<"PostMetadata">
  postId?: Prisma.StringFilter<"PostMetadata"> | string
  post?: Prisma.XOR<Prisma.PostScalarRelationFilter, Prisma.PostWhereInput>
}

export type PostMetadataOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  seoDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  post?: Prisma.PostOrderByWithRelationInput
}

export type PostMetadataWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  postId?: string
  AND?: Prisma.PostMetadataWhereInput | Prisma.PostMetadataWhereInput[]
  OR?: Prisma.PostMetadataWhereInput[]
  NOT?: Prisma.PostMetadataWhereInput | Prisma.PostMetadataWhereInput[]
  seoDescription?: Prisma.StringNullableFilter<"PostMetadata"> | string | null
  coverImage?: Prisma.StringNullableFilter<"PostMetadata"> | string | null
  tags?: Prisma.StringNullableListFilter<"PostMetadata">
  post?: Prisma.XOR<Prisma.PostScalarRelationFilter, Prisma.PostWhereInput>
}, "id" | "postId">

export type PostMetadataOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  seoDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  _count?: Prisma.PostMetadataCountOrderByAggregateInput
  _max?: Prisma.PostMetadataMaxOrderByAggregateInput
  _min?: Prisma.PostMetadataMinOrderByAggregateInput
}

export type PostMetadataScalarWhereWithAggregatesInput = {
  AND?: Prisma.PostMetadataScalarWhereWithAggregatesInput | Prisma.PostMetadataScalarWhereWithAggregatesInput[]
  OR?: Prisma.PostMetadataScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PostMetadataScalarWhereWithAggregatesInput | Prisma.PostMetadataScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PostMetadata"> | string
  seoDescription?: Prisma.StringNullableWithAggregatesFilter<"PostMetadata"> | string | null
  coverImage?: Prisma.StringNullableWithAggregatesFilter<"PostMetadata"> | string | null
  tags?: Prisma.StringNullableListFilter<"PostMetadata">
  postId?: Prisma.StringWithAggregatesFilter<"PostMetadata"> | string
}

export type PostMetadataCreateInput = {
  id?: string
  seoDescription?: string | null
  coverImage?: string | null
  tags?: Prisma.PostMetadataCreatetagsInput | string[]
  post: Prisma.PostCreateNestedOneWithoutMetadataInput
}

export type PostMetadataUncheckedCreateInput = {
  id?: string
  seoDescription?: string | null
  coverImage?: string | null
  tags?: Prisma.PostMetadataCreatetagsInput | string[]
  postId: string
}

export type PostMetadataUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seoDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.PostMetadataUpdatetagsInput | string[]
  post?: Prisma.PostUpdateOneRequiredWithoutMetadataNestedInput
}

export type PostMetadataUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seoDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.PostMetadataUpdatetagsInput | string[]
  postId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PostMetadataCreateManyInput = {
  id?: string
  seoDescription?: string | null
  coverImage?: string | null
  tags?: Prisma.PostMetadataCreatetagsInput | string[]
  postId: string
}

export type PostMetadataUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seoDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.PostMetadataUpdatetagsInput | string[]
}

export type PostMetadataUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seoDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.PostMetadataUpdatetagsInput | string[]
  postId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PostMetadataNullableScalarRelationFilter = {
  is?: Prisma.PostMetadataWhereInput | null
  isNot?: Prisma.PostMetadataWhereInput | null
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type PostMetadataCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  seoDescription?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type PostMetadataMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  seoDescription?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type PostMetadataMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  seoDescription?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type PostMetadataCreateNestedOneWithoutPostInput = {
  create?: Prisma.XOR<Prisma.PostMetadataCreateWithoutPostInput, Prisma.PostMetadataUncheckedCreateWithoutPostInput>
  connectOrCreate?: Prisma.PostMetadataCreateOrConnectWithoutPostInput
  connect?: Prisma.PostMetadataWhereUniqueInput
}

export type PostMetadataUncheckedCreateNestedOneWithoutPostInput = {
  create?: Prisma.XOR<Prisma.PostMetadataCreateWithoutPostInput, Prisma.PostMetadataUncheckedCreateWithoutPostInput>
  connectOrCreate?: Prisma.PostMetadataCreateOrConnectWithoutPostInput
  connect?: Prisma.PostMetadataWhereUniqueInput
}

export type PostMetadataUpdateOneWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.PostMetadataCreateWithoutPostInput, Prisma.PostMetadataUncheckedCreateWithoutPostInput>
  connectOrCreate?: Prisma.PostMetadataCreateOrConnectWithoutPostInput
  upsert?: Prisma.PostMetadataUpsertWithoutPostInput
  disconnect?: Prisma.PostMetadataWhereInput | boolean
  delete?: Prisma.PostMetadataWhereInput | boolean
  connect?: Prisma.PostMetadataWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PostMetadataUpdateToOneWithWhereWithoutPostInput, Prisma.PostMetadataUpdateWithoutPostInput>, Prisma.PostMetadataUncheckedUpdateWithoutPostInput>
}

export type PostMetadataUncheckedUpdateOneWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.PostMetadataCreateWithoutPostInput, Prisma.PostMetadataUncheckedCreateWithoutPostInput>
  connectOrCreate?: Prisma.PostMetadataCreateOrConnectWithoutPostInput
  upsert?: Prisma.PostMetadataUpsertWithoutPostInput
  disconnect?: Prisma.PostMetadataWhereInput | boolean
  delete?: Prisma.PostMetadataWhereInput | boolean
  connect?: Prisma.PostMetadataWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PostMetadataUpdateToOneWithWhereWithoutPostInput, Prisma.PostMetadataUpdateWithoutPostInput>, Prisma.PostMetadataUncheckedUpdateWithoutPostInput>
}

export type PostMetadataCreatetagsInput = {
  set: string[]
}

export type PostMetadataUpdatetagsInput = {
  set?: string[]
  push?: string | string[]
}

export type PostMetadataCreateWithoutPostInput = {
  id?: string
  seoDescription?: string | null
  coverImage?: string | null
  tags?: Prisma.PostMetadataCreatetagsInput | string[]
}

export type PostMetadataUncheckedCreateWithoutPostInput = {
  id?: string
  seoDescription?: string | null
  coverImage?: string | null
  tags?: Prisma.PostMetadataCreatetagsInput | string[]
}

export type PostMetadataCreateOrConnectWithoutPostInput = {
  where: Prisma.PostMetadataWhereUniqueInput
  create: Prisma.XOR<Prisma.PostMetadataCreateWithoutPostInput, Prisma.PostMetadataUncheckedCreateWithoutPostInput>
}

export type PostMetadataUpsertWithoutPostInput = {
  update: Prisma.XOR<Prisma.PostMetadataUpdateWithoutPostInput, Prisma.PostMetadataUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.PostMetadataCreateWithoutPostInput, Prisma.PostMetadataUncheckedCreateWithoutPostInput>
  where?: Prisma.PostMetadataWhereInput
}

export type PostMetadataUpdateToOneWithWhereWithoutPostInput = {
  where?: Prisma.PostMetadataWhereInput
  data: Prisma.XOR<Prisma.PostMetadataUpdateWithoutPostInput, Prisma.PostMetadataUncheckedUpdateWithoutPostInput>
}

export type PostMetadataUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seoDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.PostMetadataUpdatetagsInput | string[]
}

export type PostMetadataUncheckedUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seoDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.PostMetadataUpdatetagsInput | string[]
}



export type PostMetadataSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  seoDescription?: boolean
  coverImage?: boolean
  tags?: boolean
  postId?: boolean
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["postMetadata"]>

export type PostMetadataSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  seoDescription?: boolean
  coverImage?: boolean
  tags?: boolean
  postId?: boolean
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["postMetadata"]>

export type PostMetadataSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  seoDescription?: boolean
  coverImage?: boolean
  tags?: boolean
  postId?: boolean
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["postMetadata"]>

export type PostMetadataSelectScalar = {
  id?: boolean
  seoDescription?: boolean
  coverImage?: boolean
  tags?: boolean
  postId?: boolean
}

export type PostMetadataOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "seoDescription" | "coverImage" | "tags" | "postId", ExtArgs["result"]["postMetadata"]>
export type PostMetadataInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}
export type PostMetadataIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}
export type PostMetadataIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}

export type $PostMetadataPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PostMetadata"
  objects: {
    post: Prisma.$PostPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    seoDescription: string | null
    coverImage: string | null
    tags: string[]
    postId: string
  }, ExtArgs["result"]["postMetadata"]>
  composites: {}
}

export type PostMetadataGetPayload<S extends boolean | null | undefined | PostMetadataDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload, S>

export type PostMetadataCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PostMetadataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PostMetadataCountAggregateInputType | true
  }

export interface PostMetadataDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PostMetadata'], meta: { name: 'PostMetadata' } }
  /**
   * Find zero or one PostMetadata that matches the filter.
   * @param {PostMetadataFindUniqueArgs} args - Arguments to find a PostMetadata
   * @example
   * // Get one PostMetadata
   * const postMetadata = await prisma.postMetadata.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PostMetadataFindUniqueArgs>(args: Prisma.SelectSubset<T, PostMetadataFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PostMetadataClient<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PostMetadata that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PostMetadataFindUniqueOrThrowArgs} args - Arguments to find a PostMetadata
   * @example
   * // Get one PostMetadata
   * const postMetadata = await prisma.postMetadata.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PostMetadataFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PostMetadataFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PostMetadataClient<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PostMetadata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostMetadataFindFirstArgs} args - Arguments to find a PostMetadata
   * @example
   * // Get one PostMetadata
   * const postMetadata = await prisma.postMetadata.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PostMetadataFindFirstArgs>(args?: Prisma.SelectSubset<T, PostMetadataFindFirstArgs<ExtArgs>>): Prisma.Prisma__PostMetadataClient<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PostMetadata that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostMetadataFindFirstOrThrowArgs} args - Arguments to find a PostMetadata
   * @example
   * // Get one PostMetadata
   * const postMetadata = await prisma.postMetadata.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PostMetadataFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PostMetadataFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PostMetadataClient<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PostMetadata that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostMetadataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PostMetadata
   * const postMetadata = await prisma.postMetadata.findMany()
   * 
   * // Get first 10 PostMetadata
   * const postMetadata = await prisma.postMetadata.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const postMetadataWithIdOnly = await prisma.postMetadata.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PostMetadataFindManyArgs>(args?: Prisma.SelectSubset<T, PostMetadataFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PostMetadata.
   * @param {PostMetadataCreateArgs} args - Arguments to create a PostMetadata.
   * @example
   * // Create one PostMetadata
   * const PostMetadata = await prisma.postMetadata.create({
   *   data: {
   *     // ... data to create a PostMetadata
   *   }
   * })
   * 
   */
  create<T extends PostMetadataCreateArgs>(args: Prisma.SelectSubset<T, PostMetadataCreateArgs<ExtArgs>>): Prisma.Prisma__PostMetadataClient<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PostMetadata.
   * @param {PostMetadataCreateManyArgs} args - Arguments to create many PostMetadata.
   * @example
   * // Create many PostMetadata
   * const postMetadata = await prisma.postMetadata.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PostMetadataCreateManyArgs>(args?: Prisma.SelectSubset<T, PostMetadataCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PostMetadata and returns the data saved in the database.
   * @param {PostMetadataCreateManyAndReturnArgs} args - Arguments to create many PostMetadata.
   * @example
   * // Create many PostMetadata
   * const postMetadata = await prisma.postMetadata.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PostMetadata and only return the `id`
   * const postMetadataWithIdOnly = await prisma.postMetadata.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PostMetadataCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PostMetadataCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PostMetadata.
   * @param {PostMetadataDeleteArgs} args - Arguments to delete one PostMetadata.
   * @example
   * // Delete one PostMetadata
   * const PostMetadata = await prisma.postMetadata.delete({
   *   where: {
   *     // ... filter to delete one PostMetadata
   *   }
   * })
   * 
   */
  delete<T extends PostMetadataDeleteArgs>(args: Prisma.SelectSubset<T, PostMetadataDeleteArgs<ExtArgs>>): Prisma.Prisma__PostMetadataClient<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PostMetadata.
   * @param {PostMetadataUpdateArgs} args - Arguments to update one PostMetadata.
   * @example
   * // Update one PostMetadata
   * const postMetadata = await prisma.postMetadata.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PostMetadataUpdateArgs>(args: Prisma.SelectSubset<T, PostMetadataUpdateArgs<ExtArgs>>): Prisma.Prisma__PostMetadataClient<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PostMetadata.
   * @param {PostMetadataDeleteManyArgs} args - Arguments to filter PostMetadata to delete.
   * @example
   * // Delete a few PostMetadata
   * const { count } = await prisma.postMetadata.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PostMetadataDeleteManyArgs>(args?: Prisma.SelectSubset<T, PostMetadataDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PostMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostMetadataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PostMetadata
   * const postMetadata = await prisma.postMetadata.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PostMetadataUpdateManyArgs>(args: Prisma.SelectSubset<T, PostMetadataUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PostMetadata and returns the data updated in the database.
   * @param {PostMetadataUpdateManyAndReturnArgs} args - Arguments to update many PostMetadata.
   * @example
   * // Update many PostMetadata
   * const postMetadata = await prisma.postMetadata.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PostMetadata and only return the `id`
   * const postMetadataWithIdOnly = await prisma.postMetadata.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PostMetadataUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PostMetadataUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PostMetadata.
   * @param {PostMetadataUpsertArgs} args - Arguments to update or create a PostMetadata.
   * @example
   * // Update or create a PostMetadata
   * const postMetadata = await prisma.postMetadata.upsert({
   *   create: {
   *     // ... data to create a PostMetadata
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PostMetadata we want to update
   *   }
   * })
   */
  upsert<T extends PostMetadataUpsertArgs>(args: Prisma.SelectSubset<T, PostMetadataUpsertArgs<ExtArgs>>): Prisma.Prisma__PostMetadataClient<runtime.Types.Result.GetResult<Prisma.$PostMetadataPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PostMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostMetadataCountArgs} args - Arguments to filter PostMetadata to count.
   * @example
   * // Count the number of PostMetadata
   * const count = await prisma.postMetadata.count({
   *   where: {
   *     // ... the filter for the PostMetadata we want to count
   *   }
   * })
  **/
  count<T extends PostMetadataCountArgs>(
    args?: Prisma.Subset<T, PostMetadataCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PostMetadataCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PostMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostMetadataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PostMetadataAggregateArgs>(args: Prisma.Subset<T, PostMetadataAggregateArgs>): Prisma.PrismaPromise<GetPostMetadataAggregateType<T>>

  /**
   * Group by PostMetadata.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PostMetadataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PostMetadataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PostMetadataGroupByArgs['orderBy'] }
      : { orderBy?: PostMetadataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PostMetadataGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPostMetadataGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PostMetadata model
 */
readonly fields: PostMetadataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PostMetadata.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PostMetadataClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  post<T extends Prisma.PostDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PostDefaultArgs<ExtArgs>>): Prisma.Prisma__PostClient<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PostMetadata model
 */
export interface PostMetadataFieldRefs {
  readonly id: Prisma.FieldRef<"PostMetadata", 'String'>
  readonly seoDescription: Prisma.FieldRef<"PostMetadata", 'String'>
  readonly coverImage: Prisma.FieldRef<"PostMetadata", 'String'>
  readonly tags: Prisma.FieldRef<"PostMetadata", 'String[]'>
  readonly postId: Prisma.FieldRef<"PostMetadata", 'String'>
}
    

// Custom InputTypes
/**
 * PostMetadata findUnique
 */
export type PostMetadataFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * Filter, which PostMetadata to fetch.
   */
  where: Prisma.PostMetadataWhereUniqueInput
}

/**
 * PostMetadata findUniqueOrThrow
 */
export type PostMetadataFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * Filter, which PostMetadata to fetch.
   */
  where: Prisma.PostMetadataWhereUniqueInput
}

/**
 * PostMetadata findFirst
 */
export type PostMetadataFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * Filter, which PostMetadata to fetch.
   */
  where?: Prisma.PostMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostMetadata to fetch.
   */
  orderBy?: Prisma.PostMetadataOrderByWithRelationInput | Prisma.PostMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PostMetadata.
   */
  cursor?: Prisma.PostMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostMetadata.
   */
  distinct?: Prisma.PostMetadataScalarFieldEnum | Prisma.PostMetadataScalarFieldEnum[]
}

/**
 * PostMetadata findFirstOrThrow
 */
export type PostMetadataFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * Filter, which PostMetadata to fetch.
   */
  where?: Prisma.PostMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostMetadata to fetch.
   */
  orderBy?: Prisma.PostMetadataOrderByWithRelationInput | Prisma.PostMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PostMetadata.
   */
  cursor?: Prisma.PostMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostMetadata.
   */
  distinct?: Prisma.PostMetadataScalarFieldEnum | Prisma.PostMetadataScalarFieldEnum[]
}

/**
 * PostMetadata findMany
 */
export type PostMetadataFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * Filter, which PostMetadata to fetch.
   */
  where?: Prisma.PostMetadataWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PostMetadata to fetch.
   */
  orderBy?: Prisma.PostMetadataOrderByWithRelationInput | Prisma.PostMetadataOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PostMetadata.
   */
  cursor?: Prisma.PostMetadataWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PostMetadata from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PostMetadata.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PostMetadata.
   */
  distinct?: Prisma.PostMetadataScalarFieldEnum | Prisma.PostMetadataScalarFieldEnum[]
}

/**
 * PostMetadata create
 */
export type PostMetadataCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * The data needed to create a PostMetadata.
   */
  data: Prisma.XOR<Prisma.PostMetadataCreateInput, Prisma.PostMetadataUncheckedCreateInput>
}

/**
 * PostMetadata createMany
 */
export type PostMetadataCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PostMetadata.
   */
  data: Prisma.PostMetadataCreateManyInput | Prisma.PostMetadataCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PostMetadata createManyAndReturn
 */
export type PostMetadataCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * The data used to create many PostMetadata.
   */
  data: Prisma.PostMetadataCreateManyInput | Prisma.PostMetadataCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PostMetadata update
 */
export type PostMetadataUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * The data needed to update a PostMetadata.
   */
  data: Prisma.XOR<Prisma.PostMetadataUpdateInput, Prisma.PostMetadataUncheckedUpdateInput>
  /**
   * Choose, which PostMetadata to update.
   */
  where: Prisma.PostMetadataWhereUniqueInput
}

/**
 * PostMetadata updateMany
 */
export type PostMetadataUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PostMetadata.
   */
  data: Prisma.XOR<Prisma.PostMetadataUpdateManyMutationInput, Prisma.PostMetadataUncheckedUpdateManyInput>
  /**
   * Filter which PostMetadata to update
   */
  where?: Prisma.PostMetadataWhereInput
  /**
   * Limit how many PostMetadata to update.
   */
  limit?: number
}

/**
 * PostMetadata updateManyAndReturn
 */
export type PostMetadataUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * The data used to update PostMetadata.
   */
  data: Prisma.XOR<Prisma.PostMetadataUpdateManyMutationInput, Prisma.PostMetadataUncheckedUpdateManyInput>
  /**
   * Filter which PostMetadata to update
   */
  where?: Prisma.PostMetadataWhereInput
  /**
   * Limit how many PostMetadata to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PostMetadata upsert
 */
export type PostMetadataUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * The filter to search for the PostMetadata to update in case it exists.
   */
  where: Prisma.PostMetadataWhereUniqueInput
  /**
   * In case the PostMetadata found by the `where` argument doesn't exist, create a new PostMetadata with this data.
   */
  create: Prisma.XOR<Prisma.PostMetadataCreateInput, Prisma.PostMetadataUncheckedCreateInput>
  /**
   * In case the PostMetadata was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PostMetadataUpdateInput, Prisma.PostMetadataUncheckedUpdateInput>
}

/**
 * PostMetadata delete
 */
export type PostMetadataDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
  /**
   * Filter which PostMetadata to delete.
   */
  where: Prisma.PostMetadataWhereUniqueInput
}

/**
 * PostMetadata deleteMany
 */
export type PostMetadataDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PostMetadata to delete
   */
  where?: Prisma.PostMetadataWhereInput
  /**
   * Limit how many PostMetadata to delete.
   */
  limit?: number
}

/**
 * PostMetadata without action
 */
export type PostMetadataDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PostMetadata
   */
  select?: Prisma.PostMetadataSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PostMetadata
   */
  omit?: Prisma.PostMetadataOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostMetadataInclude<ExtArgs> | null
}
